[general]
fullscreen = false
early-exit = false
initial-tool = "rectangle"
copy-command = "wl-copy"
annotation-size-factor = 1.0
save-after-copy = false
default-hide-toolbars = false
primary-highlighter = "block"
disable-notifications = false
no-window-decoration = false
actions-on-enter = ["exit"]

